"""Adapter for OpenAI Codex CLI (`codex exec`)."""

from __future__ import annotations

import json
import tomllib
from pathlib import Path
from typing import Any

from orchestrator.agents.base import (
    AgentRequest,
    AgentResult,
    Capabilities,
    Problem,
    extract_json,
    run_process,
    tail,
)
from orchestrator.agents.runners import common
from orchestrator.config.schema import RoleConfig

MIN_VERSION = "0.100.0"


def _toml_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {_toml_value(x)}" for k, x in v.items()) + " }"
    return json.dumps(str(v))


def render_config_toml(mcp_servers: dict[str, dict[str, Any]], deny_tools: dict[str, list[str]]) -> str:
    """A minimal config.toml holding only the allowed MCP servers and per-tool denials."""
    lines = ["# Generated by the orchestrator for one run. Do not edit.", ""]
    for name, table in mcp_servers.items():
        scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
        nested = {k: v for k, v in table.items() if isinstance(v, dict)}
        lines.append(
            f"[mcp_servers.{json.dumps(name)}]" if not name.isidentifier() else f"[mcp_servers.{name}]"
        )
        for k, v in scalars.items():
            lines.append(f"{k} = {_toml_value(v)}")
        lines.append("")
        for sub, subtable in nested.items():
            if sub == "tools":
                continue
            lines.append(f"[mcp_servers.{name}.{sub}]")
            for k, v in subtable.items():
                lines.append(f"{k} = {_toml_value(v)}")
            lines.append("")
        tools = dict(nested.get("tools", {}))
        for tool in deny_tools.get(name, []):
            tools[tool] = {**tools.get(tool, {}), "enabled": False}
        for tool, ttable in tools.items():
            lines.append(f"[mcp_servers.{name}.tools.{tool}]")
            for k, v in ttable.items():
                lines.append(f"{k} = {_toml_value(v)}")
            lines.append("")
    return "\n".join(lines)


def render_rules(deny_commands: list[str]) -> str:
    """An execpolicy rules file forbidding the reserved commands."""
    out = ["# Generated by the orchestrator for one run."]
    for cmd in deny_commands:
        parts = cmd.strip().split()
        if not parts:
            continue
        pattern = ", ".join(json.dumps(p) for p in parts)
        out.append(f'prefix_rule(pattern=[{pattern}], decision="forbidden")')
    return "\n".join(out) + "\n"


class CodexRunner:
    name = "codex"
    api_key_var = "OPENAI_API_KEY"
    capabilities = Capabilities(
        structured_output=True,
        session_resume=True,
        turn_cap=False,
        budget_cap=False,
        usage_report=True,
        read_only_mode=True,
        command_deny_hooks=True,
        config_dir_isolation=True,
    )

    def preflight(self, role: RoleConfig) -> list[Problem]:
        problems = common.binary_problems("codex", MIN_VERSION, role)
        problems += common.soft_limit_warnings(role, turn_cap=False, budget_cap=False)
        return problems

    async def _ensure_login(self, home: Path, env: dict[str, str], api_key: str | None) -> None:
        if (home / "auth.json").exists() or not api_key:
            return
        await run_process(
            ["codex", "login", "--with-api-key"],
            cwd=home,
            env=env,
            timeout=60,
            stdin_text=api_key + "\n",
        )

    def argv(self, request: AgentRequest, home: Path) -> list[str]:
        schema_path = home / "schema.json"
        schema_path.write_text(json.dumps(request.schema))
        sandbox = "read-only" if request.access.worktree == "read-only" else "workspace-write"
        argv = ["codex", "exec"]
        if request.session:
            argv += ["resume", request.session]
        argv += [
            "--cd",
            str(request.cwd),
            "--json",
            "--output-last-message",
            str(request.run_dir / "last-message.txt"),
        ]
        if not request.session:
            argv += ["--sandbox", sandbox, "--output-schema", str(schema_path)]
            if request.role == "reviewer":
                argv.append("--ephemeral")
            for p in request.access.writable_paths:
                argv += ["--add-dir", str(p)]
        else:
            argv += ["-c", f"sandbox_mode={json.dumps(sandbox)}"]
        if request.model:
            argv += ["--model", request.model]
        effort = request.options.get("reasoning_effort")
        if effort:
            argv += ["-c", f"model_reasoning_effort={json.dumps(effort)}"]
        argv.append("-")
        return argv

    async def run(self, request: AgentRequest) -> AgentResult:
        home = common.config_home(request, "codex-home")
        (home / "config.toml").write_text(render_config_toml(request.mcp_servers, request.deny_tools))
        rules_dir = home / "rules"
        rules_dir.mkdir(exist_ok=True)
        (rules_dir / "orchestrator.rules").write_text(
            render_rules(request.deny_commands or common.DEFAULT_DENY_COMMANDS)
        )
        env = dict(request.env)
        env["CODEX_HOME"] = str(home)
        await self._ensure_login(home, env, env.get("OPENAI_API_KEY"))
        argv = self.argv(request, home)
        (request.run_dir / "argv.json").write_text(json.dumps(argv, indent=2))
        prompt = request.prompt
        if request.session:
            prompt = request.prompt  # schema was fixed when the session was created
        outcome = await run_process(
            argv,
            cwd=request.cwd,
            env=env,
            timeout=request.limits.timeout_seconds,
            stdin_text=prompt,
            stdout_path=request.run_dir / "events.jsonl",
            stderr_path=request.run_dir / "stderr.log",
        )
        if outcome.timed_out:
            return AgentResult(False, "timeout", stderr_tail=tail(outcome.stderr))
        session_id, usage = self._parse_events(outcome.stdout)
        last_path = request.run_dir / "last-message.txt"
        raw = last_path.read_text() if last_path.exists() else outcome.stdout
        structured = extract_json(raw)
        ok = outcome.exit_code == 0 and structured is not None
        return AgentResult(
            ok=ok,
            termination="completed" if outcome.exit_code == 0 else "error",
            raw_text=raw,
            structured_output=structured,
            session_id=session_id,
            cost_usd=None,
            num_turns=None,
            usage=usage,
            exit_code=outcome.exit_code,
            stderr_tail=tail(outcome.stderr),
            error=None
            if ok
            else (f"codex exited {outcome.exit_code}" if outcome.exit_code else "no JSON result"),
        )

    @staticmethod
    def _parse_events(text: str) -> tuple[str | None, dict[str, Any]]:
        session_id = None
        usage: dict[str, Any] = {}
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            t = ev.get("type", "")
            if t == "thread.started":
                session_id = ev.get("thread_id") or session_id
            elif t == "turn.completed" and isinstance(ev.get("usage"), dict):
                for k, v in ev["usage"].items():
                    if isinstance(v, (int, float)):
                        usage[k] = usage.get(k, 0) + v
        return session_id, usage


def load_codex_mcp_sources(paths: list[Path]) -> dict[str, dict[str, Any]]:
    """Raw [mcp_servers.<name>] tables from Codex config files."""
    found: dict[str, dict[str, Any]] = {}
    for p in paths:
        if not p.exists():
            continue
        with p.open("rb") as f:
            data = tomllib.load(f)
        for name, table in (data.get("mcp_servers") or {}).items():
            found.setdefault(name, table)
    return found
